FROM node:20

WORKDIR /app

# Copy package + install
COPY package*.json ./
RUN npm install

# Copy all files
COPY . .

# Build using .env values
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]

