FROM node:20

WORKDIR /app

# Copy .env FIRST (เพื่อให้ build ใช้ได้)
COPY .env .env

# Copy package + install
COPY package*.json ./
RUN npm install

# Copy all files
COPY . .

# Build using .env values
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]

